=== 로그인 페이지 요청

API : `GET /api/oauth/login`


=== `301 MOVED_PERMANENTLY`

==== `Request`

operation::o_auth_login_documentation_test/redirect_to_social_login_page[snippets='http-request']

==== `Response`

operation::o_auth_login_documentation_test/redirect_to_social_login_page[snippets='http-response']


=== 유저 로그인 콜백

API : `GET /api/oauth/callback`


=== `200 OK`

==== `Request`

operation::o_auth_login_documentation_test/user_login_success[snippets='http-request,request-parameters']

==== `Response`

operation::o_auth_login_documentation_test/user_login_success[snippets='http-response,response-fields']


=== 액세스 토큰 갱신

API : `GET /api/oauth/refresh`


=== `200 OK`

==== `Request`

operation::o_auth_update_token_documentation_test/update_access_token_success[snippets='http-request,request-headers']

==== `Response`

operation::o_auth_update_token_documentation_test/update_access_token_success[snippets='http-response,response-fields']


=== `400 BAD_REQUEST`

==== `Request`

operation::o_auth_update_token_documentation_test/update_access_token_fail_expired_token[snippets='http-request,request-headers']

==== `Response`

operation::o_auth_update_token_documentation_test/update_access_token_fail_expired_token[snippets='http-response,response-fields']

=== `404 NOT_FOUND`

==== `Request`

operation::o_auth_update_token_documentation_test/update_access_token_fail_user_not_found[snippets='http-request,request-headers']

==== `Response`

operation::o_auth_update_token_documentation_test/update_access_token_fail_user_not_found[snippets='http-response,response-fields']
