export const STATUS_CODE = {
  SUCCESS: {
    LOGIN: 'T-O001',
    REISSUE_ACCESS_TOKEN: 'T-O002',
    MY_USER_PROFILE: 'T-U005',
    LIKE: 'T-R006',
    CANCEL_LIKE: 'T-R007',
  },
  FAILURE: {
    COMMUNICATION_WITH_OAUTH_SERVER: 'F-O001',
    EXPIRED_ACCESS_TOKEN: 'F-O003',
    NEED_TO_LOGIN: 'F-O004',
  },
};

export const SUCCESS_STATUS_CODES = Object.values(STATUS_CODE.SUCCESS);
export const FAILURE_STATUS_CODES = Object.values(STATUS_CODE.FAILURE);
