=== 리뷰 생성

API : `POST /api/reviews`


=== `201 CREATED`

==== `Request`

operation::review_insert_acceptance_test/create_review_success[snippets='http-request,request-fields']

==== `Response`

operation::review_insert_acceptance_test/create_review_success[snippets='http-response,response-fields']

=== 리뷰 수정

API : `PUT /api/reviews/{reviewId}`

=== `200 OK`

리뷰 작성자가 리뷰 수정한 경우

==== `Request`

operation::review_modify_acceptance_test/modify_review_success[snippets='http-request,path-parameters,request-fields']

==== `Response`

operation::review_modify_acceptance_test/modify_review_success[snippets='http-response,response-fields']

=== `401 UNATHORIZED`

리뷰 작성자가 아닌 유저가 수정 요청한 경우


==== `Request`

operation::review_modify_acceptance_test/modify_review_failed[snippets='http-request']

==== `Response`

operation::review_modify_acceptance_test/modify_review_failed[snippets='http-response,response-fields']

=== 리뷰 삭제

API : `DELETE /api/reviews/{reviewId}`

=== `200 OK`

리뷰 작성자가 리뷰 삭제한 경우

==== `Request`

operation::review_remove_accecptance_test/remove_review_success[snippets='http-request']

==== `Response`

operation::review_remove_accecptance_test/remove_review_success[snippets='http-response,response-fields']

=== `401 UNATHORIZED`

비회원이 리뷰 삭제 요청한 경우

==== `Request`

operation::review_remove_accecptance_test/remove_review_failed_need_login[snippets='http-request']

==== `Response`

operation::review_remove_accecptance_test/remove_review_failed_need_login[snippets='http-response,response-fields']
