=== 댓글 조회 (GET /api/reviews/{reviewId}/comments)

API : `GET /api/reviews/{reviewId}/comments`

특정 리뷰에 달린 댓글을 조회합니다.

==== 200 OK

===== Request

operation::comment_search_documentation_test/search_comment_success[snippets='http-request,path-parameters,request-parameters']

===== Response

operation::comment_search_documentation_test/search_comment_success[snippets='http-response,response-fields']

=== 댓글 생성 (POST /api/reviews/{reviedId}/comments)

API : `POST /api/reviews/{reviewId}/comments`

특정 id의 리뷰에 댓글을 작성합니다. (단, 로그인한 사용자만 가능)

==== `201 CREATED`

===== Request

operation::comment_create_documentation_test/create_comment_success[snippets='http-request,request-body,path-parameters']

===== Response

operation::comment_create_documentation_test/create_comment_success[snippets='http-response,response-fields']

=== 댓글 수정 (PUT /api/reviews/{reviewId}/comments/{commentId})

API : `PUT /api/reviews/{reviewId}/comments/{commentId}`

특정 리뷰에 달린 특정 댓글을 수정합니다. (단, 로그인한 사용자만 가능)


==== `200 OK`

===== Request

operation::comment_modify_documentation_test/modify_comment_success[snippets='http-request,request-body,path-parameters']

===== Response

operation::comment_modify_documentation_test/modify_comment_success[snippets='http-response,response-fields']

=== 댓글 삭제 (DELETE /api/reviews/{reviewId}/comments/{commentId})

API : `DELETE /api/reviews/{reviewId}/comments/{commentId}`

==== `200 OK`

===== Request

operation::comment_remove_documentation_test/remove_comment_success[snippets='http-request,path-parameters']

===== Response

operation::comment_remove_documentation_test/remove_comment_success[snippets='http-response,response-fields']

