=== 댓글 생성

API : `POST /api/reviews/{reviewId}/comments`

=== `201 CREATED`

==== `Request`

operation::comment_create_acceptance_test/create_comment_success[snippets='http-request,request-body,path-parameters']

==== `Response`

operation::comment_create_acceptance_test/create_comment_success[snippets='http-response,response-fields']

=== 댓글 수정

API : `PUT /api/reviews/{reviewId}/comments/{commentId}`

=== `200 OK`

==== `Request`

operation::comment_modify_acceptance_test/modify_comment_success[snippets='http-request,request-body,path-parameters']

==== `Response`

operation::comment_modify_acceptance_test/modify_comment_success[snippets='http-response,response-fields']

=== 댓글 삭제

API : `DELETE /api/reviews/{reviewId}/comments/{commentId}`

=== `200 OK`

==== `Request`

operation::comment_remove_acceptance_test/remove_comment_success[snippets='http-request,path-parameters']

==== `Response`

operation::comment_remove_acceptance_test/remove_comment_success[snippets='http-response,response-fields']

=== 댓글 조회

API : `GET /api/reviews/{reviewId}/comments`

=== `200 OK`

==== `Request`

operation::comment_search_acceptance_test/search_comment_success[snippets='http-request,path-parameters,request-parameters']

==== `Response`

operation::comment_search_acceptance_test/search_comment_success[snippets='http-response,response-fields']
