=== 전체 목록 (/api/users/*)

[cols=2*]
|===
| 기능 | API

| <<유저 검색>> | GET /api/users?nickname={value}
| <<유저가 작성한 리뷰들 조회>> | GET /api/users/{userId}/reviews?after={value}&size={value}
| <<위치기반 유저가 작성한 리뷰들 조회>> | GET /api/users/{userId}/reviews?type=maps&latitude={value}&longitude={value}&after={value}&size={value}
| <<유저 본인 프로필 조회>> | GET /api/users/me
| <<유저 프로필 조회>> | GET /api/users/{userId}
| <<유저 프로필 수정 요청>> | PUT /api/users
| <<유저 탈퇴>> | DELETE /api/users
| <<유저 팔로워 목록 조회>> | GET /api/users/{userId}/followers
| <<유저 팔로잉 목록 조회>> | GET /api/users/{userId}/followings
| <<유저 팔로우 요청>> | PUT /api/users/follow
| <<유저 언팔로우 요청>> | PUT /api/users/follow

|===

=== 유저 검색

API : `GET /api/users?nickname={value}

유저들을 닉네임으로 검색합니다.

==== `200 OK`

===== Request

operation::user_search_documentation_test/search_user_by_nickname_success[snippets='http-request,request-parameters']

===== Response

operation::user_search_documentation_test/search_user_by_nickname_success[snippets='http-response,response-fields']


=== 유저가 작성한 리뷰들 조회

API : `GET /api/users/{userId}/reviews?after={value}&size={value}`

특정 유저의 모든 리뷰를 조회합니다.

게스트이거나 친구가 아닌 경우 : public 게시물 조회

친구인 경우 : public | protected 게시물 조회

본인의 경우 : public | protected | private 전체 게시물 조회

==== `200 OK` : 게스트가 요청한 경우

===== Request

operation::user_reviews_search_by_user_id_documentation_test/guest_search_user_reviews_success[snippets='http-request,path-parameters,request-parameters']

===== Response

operation::user_reviews_search_by_user_id_documentation_test/guest_search_user_reviews_success[snippets='http-response,response-fields']


==== `200 OK` : 본인이 요청한 경우

===== Request

operation::user_reviews_search_by_user_id_documentation_test/self_user_search_user_reviews_success[snippets='http-request']

===== Response

operation::user_reviews_search_by_user_id_documentation_test/self_user_search_user_reviews_success[snippets='http-response']

=== 위치기반 유저가 작성한 리뷰들 조회

API : `GET /api/users/{userId}/reviews?type=maps&y={value}&x={value}&after={value}&size={value}`

사용자의 위치를 기반으로 특정유저의 리뷰 목록을 조회합니다.
(팔로우 관계의 유저면 public|protected 공개범위, 아니면 public 공개범위의 데이터를 반환합니다.)

=== `200 OK`

=== Request

operation::user_reviews_search_by_radius_documentation_test/reviews_radius_success[snippets='http-request,path-parameters,request-parameters']

=== Response

operation::user_reviews_search_by_radius_documentation_test/reviews_radius_success[snippets='http-response,response-fields']


=== 유저 본인 프로필 조회

API : `GET /api/users/me`

유저 본인의 프로필을 조회합니다. (단, 로그인 한 유저만 가능)

==== `200 OK`

===== Request

operation::user_search_self_profile_documentation_test/search_self_profile_success[snippets='http-request']

===== Response

operation::user_search_self_profile_documentation_test/search_self_profile_success[snippets='http-response,response-fields']

=== 유저 프로필 조회

API : `GET /api/users/{userId}`

특정 유저의 프로필을 조회합니다.

==== `200 OK`

===== Request

operation::user_search_profile_documentation_test/search_user_profile_success[snippets='http-request,path-parameters']

===== Response

operation::user_search_profile_documentation_test/search_user_profile_success[snippets='http-response,response-fields']

=== 유저 프로필 수정 요청

API : `PUT /api/users`

유저 프로필을 수정합니다. (단, 로그인 한 유저만 가능)

==== `200 OK`

===== Request

operation::user_modify_documentation_test/modify_user_profile_success[snippets='http-request']

===== Response

operation::user_modify_documentation_test/modify_user_profile_success[snippets='http-response']

=== 유저 탈퇴

API : `DELETE /api/users`

유저를 탈퇴합니다. (단, 로그인 한 유저만 가능)

==== `200 OK`

===== Request

operation::user_delete_documentation_test/delete_user_success[snippets='http-request']

===== Response

operation::user_delete_documentation_test/delete_user_success[snippets='http-response']


=== 유저 팔로워 목록 조회

API : `GET /api/users/{userId}/followers`

특정 유저의 팔로우 목록을 조회합니다.

==== `200 OK`

===== Request

operation::user_followers_search_by_user_id_documentation_test/search_user_followers_success[snippets='http-request,path-parameters']

===== Response

operation::user_followers_search_by_user_id_documentation_test/search_user_followers_success[snippets='http-response,response-fields']

=== 유저 팔로잉 목록 조회

API : `GET /api/users/{userId}/followings`

특정 유저의 팔로잉 목록을 조회합니다.

==== `200 OK`

===== Request

operation::user_followings_search_by_user_id_documentation_test/search_user_followings_success[snippets='http-request,path-parameters']

===== Response

operation::user_followings_search_by_user_id_documentation_test/search_user_followings_success[snippets='http-response,response-fields']



=== 유저 팔로우 요청

API : `PUT /api/users/follow`

유저를 팔로우 합니다. (단, 로그인 한 유저만 가능)

==== `200 OK`

===== Request

operation::user_follow_unfollow_documentation_test/user_follow_success[snippets='http-request,request-body']

===== Response

operation::user_follow_unfollow_documentation_test/user_follow_success[snippets='http-response']


=== 유저 언팔로우 요청

API : `PUT /api/users/unfollow`

유저를 언팔로우 합니다. (단, 로그인 한 유저만 가능)

==== `200 OK`

===== Request

operation::user_follow_unfollow_documentation_test/user_unfollow_success[snippets='http-request,request-body']

===== Response

operation::user_follow_unfollow_documentation_test/user_unfollow_success[snippets='http-response']


