=== 유저 프로필 수정 요청

API : `PUT /api/users`


=== `200 OK`

==== `Request`

operation::user_modify_acceptance_test/modify_user_profile_success[snippets='http-request']

==== `Response`

operation::user_modify_acceptance_test/modify_user_profile_success[snippets='http-response']


=== 유저 팔로우 요청

API : `PUT /api/users/follow`


=== `200 OK`

==== `Request`

operation::user_follow_unfollow_acceptance_test/user_follow_success[snippets='http-request,request-body']

==== `Response`

operation::user_follow_unfollow_acceptance_test/user_follow_success[snippets='http-response']


=== 유저 언팔로우 요청

API : `PUT /api/users/unfollow`


=== `200 OK`

==== `Request`

operation::user_follow_unfollow_acceptance_test/user_unfollow_success[snippets='http-request,request-body']

==== `Response`

operation::user_follow_unfollow_acceptance_test/user_unfollow_success[snippets='http-response']

=== 유저 리뷰 조회

API : `GET /api/users/{userId}/reviews`

특정 유저의 모든 리뷰를 조회 기능

게스트이거나 친구가 아닌 경우 : public 게시물 조회

친구인 경우 : public | protected 게시물 조회

본인의 경우 : public | protected | private 전체 게시물 조회

=== `200 OK` : 게스트가 요청한 경우

==== `Request`

operation::user_reviews_search_by_user_id_acceptance_test/guest_search_user_reviews_success[snippets='http-request']

==== `Response`

operation::user_reviews_search_by_user_id_acceptance_test/guest_search_user_reviews_success[snippets='http-response,response-fields']


=== `200 OK` : 본인이 요청한 경우

==== `Request`

operation::user_reviews_search_by_user_id_acceptance_test/self_user_search_user_reviews_success[snippets='http-request']

==== `Response`

operation::user_reviews_search_by_user_id_acceptance_test/self_user_search_user_reviews_success[snippets='http-response']

=== 유저 프로필 조회

API : `GET /api/users/{userId}`

=== `200 OK`

==== `Request`

operation::user_search_profile_acceptance_test/search_user_profile_success[snippets='http-request,path-parameters']

==== `Response`

operation::user_search_profile_acceptance_test/search_user_profile_success[snippets='http-response,response-fields']

=== 유저 탈퇴

API : `DELETE /api/users`

=== `200 OK`

==== `Request`

operation::user_delete_acceptance_test/delete_user_success[snippets='http-request']

==== `Response`

operation::user_delete_acceptance_test/delete_user_success[snippets='http-response']

=== 유저 본인 프로필 조회

API : `GET /api/users/me`

=== `200 OK`

==== `Request`

operation::user_search_self_profile_acceptance_test/search_self_profile_success[snippets='http-request']

==== `Response`

operation::user_search_self_profile_acceptance_test/search_self_profile_success[snippets='http-response,response-fields']

=== 유저 팔로워 목록 조회

API : `GET /api/users/{userId}/followers`

=== `200 OK`

==== `Request`

operation::user_followers_search_by_user_id_acceptance_test/search_user_followers_success[snippets='http-request,path-parameters']

==== `Response`

operation::user_followers_search_by_user_id_acceptance_test/search_user_followers_success[snippets='http-response,response-fields']

=== 유저 팔로잉 목록 조회

API : `GET /api/users/{userId}/followings`

=== `200 OK`

==== `Request`

operation::user_followings_search_by_user_id_acceptance_test/search_user_followings_success[snippets='http-request,path-parameters']

==== `Response`

operation::user_followings_search_by_user_id_acceptance_test/search_user_followings_success[snippets='http-response,response-fields']

=== 유저 검색

API : `GET /api/users?nickname=xxx

=== `200 OK`

==== `Request`

operation::user_search_acceptance_test/search_user_by_nickname_success[snippets='http-request,request-parameters']

==== `Response`

operation::user_search_acceptance_test/search_user_by_nickname_success[snippets='http-response,response-fields']
