=== 가게 이름으로 가게 조회

API : `GET /api/stores`

=== `200 OK`

==== `Request`

operation::store_search_documentation_test/search_store_by_name_containing_success[snippets='http-request,request-parameters']

==== `Response`

operation::store_search_documentation_test/search_store_by_name_containing_success[snippets='http-response,response-fields']

=== 가게 추가

API : `POST /api/stores`

=== `201 CREATED`

==== `Request`

operation::store_create_documentation_test/create_store_success[snippets='http-request,request-body']

==== `Response`

operation::store_create_documentation_test/create_store_success[snippets='http-response,response-fields']

=== 가게 수정

API : `PUT /api/stores`

=== `200 SUCCESS`

==== `Request`

operation::store_modify_documentation_test/modify_store_success[snippets='http-request,path-parameters,request-body']

==== `Response`

operation::store_modify_documentation_test/modify_store_success[snippets='http-response,response-fields']

=== 가게 삭제

API : `DELETE /api/stores`

=== `200 SUCCESS`

==== `Request`

operation::store_remove_documentation_test/remove_store_success[snippets='http-request,path-parameters']

==== `Response`

operation::store_remove_documentation_test/remove_store_success[snippets='http-response,response-fields']

=== `400 BAD REQUEST`

존재하지 않는 가게를 삭제할 경우, 실패합니다.

==== `Request`

operation::store_remove_documentation_test/remove_store_failed[snippets='http-request,path-parameters']

==== `Response`

operation::store_remove_documentation_test/remove_store_failed[snippets='http-response,response-fields']

=== 가게 목록 위치 기반 조회

API : `GET /api/stores?type=maps&x=127.123&y=36.123&radius=100`

=== `200 SUCCESS`

==== `Request`

operation::store_search_by_radius_documentation_test/stores_radius_success[snippets='http-request,request-parameters']

==== `Response`

operation::store_search_by_radius_documentation_test/stores_radius_success[snippets='http-response,response-fields']

=== 가게 등록 검증

API : `PUT /api/stores`

=== `200 SUCCESS`

==== `Request`

operation::store_verify_or_save_documentation_test/search_store_by_name_containing_success[snippets='http-request,request-body']

==== `Response`

operation::store_verify_or_save_documentation_test/search_store_by_name_containing_success[snippets='http-response,response-fields']

=== 가게 상세 조회

API : `GET /api/stores/{storeId}`

=== `200 SUCCESS`

==== `Request`

operation::store_detail_documentation_test/search_store_detail_success[snippets='http-request,path-parameters']

==== `Response`

operation::store_detail_documentation_test/search_store_detail_success[snippets='http-response,response-fields']

=== 가게 리뷰 조회(GET /api/stores/\{storeId}/reviews?after=\{after}&size=\{size})

==== `Request`

operation::store_reviews_search_by_store_id_documentation_test/search_store_public_reviews_success[snippets='http-request,path-parameters,request-parameters']

==== `Response`

operation::store_reviews_search_by_store_id_documentation_test/search_store_public_reviews_success[snippets='http-response,response-fields']
