=== 전체 목록 (/api/stores/*)
[cols=2*]
|===
| 기능 | API

| <<가게 조회>> | GET /api/stores?storeName={value}
| <<가게 상세 조회>> | GET /api/stores/{storeId}
| <<가게 목록 위치 기반 조회>> | GET /api/stores?latitude={value}&longitude={value}
| <<가게 리뷰 조회>> | GET /api/stores/\{storeId}/reviews?after=\{after}&size=\{size}
| <<가게 등록 검증>> | PUT /api/stores
| <<가게 추가(ADMIN)>> | POST /api/stores
| <<가게 수정(ADMIN)>> | PUT /api/stores/{storeId}
| <<가게 삭제>> | DELETE /api/stores/{storeId}

|===

=== 가게 조회

API : `GET /api/stores`

가게 이름으로 가게를 조회합니다.

==== `200 OK`

===== Request

operation::store_search_documentation_test/search_store_by_name_containing_success[snippets='http-request,request-parameters']

===== Response

operation::store_search_documentation_test/search_store_by_name_containing_success[snippets='http-response,response-fields']

=== 가게 상세 조회

API : `GET /api/stores/{storeId}`

특정 가게의 상세 정보를 조회합니다. (단, 가게 리뷰는 가게 리뷰 조회 API를 사용해야 합니다.)

==== `200 SUCCESS`

===== Request

operation::store_detail_documentation_test/search_store_detail_success[snippets='http-request,path-parameters']

===== Response

operation::store_detail_documentation_test/search_store_detail_success[snippets='http-response,response-fields']

=== 가게 목록 위치 기반 조회

API : `GET /api/stores?type=maps&x=127.123&y=36.123&radius=100`

가게 목록을 위치 기반으로 조회합니다.

==== `200 SUCCESS`

===== Request

operation::store_search_by_radius_documentation_test/stores_radius_success[snippets='http-request,request-parameters']

===== Response

operation::store_search_by_radius_documentation_test/stores_radius_success[snippets='http-response,response-fields']

=== 가게 리뷰 조회

==== `Request`

operation::store_reviews_search_by_store_id_documentation_test/search_store_public_reviews_success[snippets='http-request,path-parameters,request-parameters']

==== `Response`

operation::store_reviews_search_by_store_id_documentation_test/search_store_public_reviews_success[snippets='http-response,response-fields']


=== 가게 등록 검증

API : `PUT /api/stores`

카카오 상점 정보를 가지고 가게 등록/검증을 합니다. (단, 어드민만 가능)

==== `200 SUCCESS`

===== Request

operation::store_verify_or_save_documentation_test/search_store_by_name_containing_success[snippets='http-request,request-body']

===== Response

operation::store_verify_or_save_documentation_test/search_store_by_name_containing_success[snippets='http-response,response-fields']



=== 가게 추가(ADMIN)

API : `POST /api/stores`

가게를 생성합니다. (단, 관리자로 등록된 사용자만 가능)

==== `201 CREATED`

===== Request

operation::store_create_documentation_test/create_store_success[snippets='http-request,request-body']

===== Response

operation::store_create_documentation_test/create_store_success[snippets='http-response,response-fields']

==== `401 UNAUTHORIZED`

===== Request

operation::store_create_documentation_test/create_store_failed[snippets='http-request,request-body']

===== Response

operation::store_create_documentation_test/create_store_failed[snippets='http-response,response-fields']

=== 가게 수정(ADMIN)

API : `PUT /api/stores/{storeId}`

특정 가게를 수정합니다. (단, 어드민만 가능)

==== `200 SUCCESS`

===== Request

operation::store_modify_documentation_test/modify_store_success[snippets='http-request,path-parameters,request-body']

===== Response

operation::store_modify_documentation_test/modify_store_success[snippets='http-response,response-fields']

==== `401 UNAUTHORIZED`

===== Request

operation::store_modify_documentation_test/modify_store_falied[snippets='http-request,request-body']

===== Response

operation::store_modify_documentation_test/modify_store_falied[snippets='http-response,response-fields']

=== 가게 삭제

API : `DELETE /api/stores`

특정 가게를 삭제합니다. (단, 어드민만 가능)

==== `200 SUCCESS`

===== Request

operation::store_remove_documentation_test/remove_store_success[snippets='http-request,path-parameters']

===== Response

operation::store_remove_documentation_test/remove_store_success[snippets='http-response,response-fields']

==== `400 BAD REQUEST`

존재하지 않는 가게를 삭제할 경우, 실패합니다.

===== Request

operation::store_remove_documentation_test/remove_store_failed[snippets='http-request,path-parameters']

===== Response

operation::store_remove_documentation_test/remove_store_failed[snippets='http-response,response-fields']

